Belindas_android-01-71-add_product_page
SeattleColleges/belindas-closet-android pull request #87
Opened 2023-10-21 00:47 UTC by Robel-003

Resolves #71 

- Updating the AddProduct page allowing users to add a product.
- The "Add Product" in the page button doesn't have any functionality. 
- The page is temporarily accessible to all users. 
- Eventually need to protect the page and the button in the home page only allowing admin to access and use the button and page.

<img width="370" alt="Screenshot 2023-10-20 at 5 42 44 PM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/116779961/515dc585-f500-4411-bbbd-b0594d9bfdd7">

<img width="369" alt="Screenshot 2023-10-20 at 5 40 43 PM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/116779961/297d64d4-a8b9-4298-b946-058bbfa57864">

2023-10-21 18:47 UTC, Annelisebx submitted a review, later dismissed

2023-10-23 07:50 UTC, taylorpapke commented on app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
>      var productName by remember { mutableStateOf("") }
I would like to change this to productType and have a drop down box with all the clothing categories. This should match our schema @ https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/schemas/product.schema.ts.

2023-10-23 07:53 UTC, taylorpapke requested changes
Looks great but I just want to change that first field. I think productName as a string got mixed into our project earlier on at some point when it was originally intended to be productType as a String[].

2023-10-24 00:23 UTC, Robel-003 commented on app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
>      var productName by remember { mutableStateOf("") }
I change the productName to productType adding these values (shirts, pants, dresses, shoes) and also created a dropdown menu when adding a new product. Only following change that would be needed is when a user is updating/editing a specific product, I would just need to create another dropdown menu for that. I can create an issue and start on that

2023-10-24 20:22 UTC, taylorpapke submitted a review, later dismissed
Thanks for making these changes!

2023-10-26 06:20 UTC, taylorpapke commented
@Robel-003 Looks like some conflicts have popped up on this one due to @tinpham5614's recent PR merge https://github.com/SeattleColleges/belindas-closet-android/pull/85

2023-10-27 21:33 UTC, Robel-003 commented
> @Robel-003 Looks like some conflicts have popped up on this one due to @tinpham5614's recent PR merge #85

just resolved the merge conflicts. If all is well, I can merge this branch

2023-10-27 21:52 UTC, taylorpapke commented
Oh no! A couple more just popped up with the other merges that just happened.

2023-10-27 21:58 UTC, Robel-003 commented
> Oh no! A couple more just popped up with the other merges that just happened.

no worries, just resolved

2023-10-27 22:06 UTC, taylorpapke approved these changes

2023-10-28 18:37 UTC, theGaryLarson commented
@taylorpapke @Robel-003 
I am unable to build this to confirm it works. Am I missing something?

AddProduct.kt -> unable to resolve ProductType.SHIRTS

2023-10-28 19:22 UTC, Robel-003 commented
> @taylorpapke @Robel-003 I am unable to build this to confirm it works. Am I missing something?
> 
> AddProduct.kt -> unable to resolve ProductType.SHIRTS ![image](https://user-images.githubusercontent.com/64063020/278832512-f2109394-8892-485a-a66d-1281b091866c.png)

it's the enum value, that enum value doesn't exist, you just have to change it to another enum value. 
But this branch might produce some errors because of the difference in variables names in the AddProduct file, like with productName and productType. I'll need to update those variable names across other pages

2023-10-30 16:23 UTC, theGaryLarson commented
I went to review this still unable to build due to the enum and variable names. Until it can build (enum and names are updated) I don't feel comfortable merging this into main. Our codebase needs to compile. @taylorpapke are you saying that it is updated in main? If so @Robel-003  I'd rebase this branch onto main so reviewers can build successfully.

2023-10-30 18:07 UTC, brinkbrink commented
Thanks @theGaryLarson I created a new issue to resolve this naming discrepancy before we merge to main. I messaged @Robel-003 and @taylorpapke about it on Slack.

2023-11-01 23:45 UTC, taylorpapke commented
@Robel-003 one last conflict to resolve here

2023-11-03 03:14 UTC, taylorpapke approved these changes
LGTM! I would ideally like to get the product name (productInfoField) removed but on another PR. Perhaps we can remove it when we add the remaining fields for the other product attributes to this screen.

2023-11-04 05:10 UTC, tinpham5614 approved these changes
LGTM!

2023-11-04 20:38 UTC, merged