Belinda_Android_Sprint_1_73_Toast_Message_For _AddProduct Button
SeattleColleges/belindas-closet-android pull request #88
Opened 2023-10-21 05:16 UTC by MuhammadNSC

Resolved: #73 
This PR displays a toast message "Successful"when user fills in all fields and when a filed is empty and error message is displayed.

![ToastMessage](https://github.com/SeattleColleges/belindas-closet-android/assets/117953848/2d0def74-6089-4f36-82d4-0ca455ef7e6c)

![ToastMessage2](https://github.com/SeattleColleges/belindas-closet-android/assets/117953848/3d1139c7-1755-462e-8d83-6b27e4375949)

2023-10-23 21:49 UTC, taylorpapke reviewed
Tested this and it looks like the proper toast message is firing as expected when the add product button is clicked. However, toast messages are also firing when the keyboard is used to enter or delete characters and when a new selection is made in the dropdown. @tinpham5614 do you have any ideas as to why this is happening?

2023-10-24 03:03 UTC, tinpham5614 requested changes

2023-10-24 03:03 UTC, tinpham5614 commented on app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
> +    if (toastMessage.isNotEmpty()) {
I believe that the Toast message displays whenever there is an action due to this if statement. Removing it will solve the error.

2023-10-25 17:39 UTC, brinkbrink commented
@taylorpapke that sounds like a good idea. There's a tiny merge conflict here with Tin's new schema I just merged in but it'd be really simple to resolve.

2023-10-25 17:45 UTC, brinkbrink commented on app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
> +    if (toastMessage.isNotEmpty()) {
Hey @MuhammadNSC once you do this we can merge yours into main and then do what Taylor suggested in a comment below of making a new issue to make this work with the upcoming change to the product schema. Does that make sense? Message Tin on Slack if you're having trouble understanding the feedback.

2023-10-25 18:49 UTC, MuhammadNSC commented
Thanks everyone for the feedback, I've fix the code and will commit it now

2023-10-25 22:31 UTC, closed without merging